language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --pull -t alvisisme/cordova-android:9.0.0 .
  - docker push alvisisme/cordova-android:9.0.0
