---
kind: pipeline
type: exec
name: Mirror
node:
  type: ubuntu20.04
steps:
- name: gitee
  commands:
    - git push --mirror git@gitee.com:alvisisme/docker-cordova-android.git
- name: github
  commands:
    - git push --mirror git@github.com:alvisisme/docker-cordova-android.git
